### ISSUE TITLE
Compile fails. Bad return status for module build on kernel

### ISSUE THREAD

**Issue by JanWerder** [luckynzm/tlwn8200nddriver#7]
The driver doesn't seem to compile. I'm on Linux plex 6.1.0-rpi4-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.54-1+rpt2 (2023-10-05) aarch64

```
root@plex:/home/jan/tlwn8200nddriver# sudo dkms add .
Deprecated feature: REMAKE_INITRD (/home/jan/tlwn8200nddriver/dkms.conf)
Deprecated feature: REMAKE_INITRD (/usr/src/rtl8192eu-1.0/dkms.conf)
Creating symlink /var/lib/dkms/rtl8192eu/1.0/source -> /usr/src/rtl8192eu-1.0
root@plex:/home/jan/tlwn8200nddriver# sudo dkms install rtl8192eu/1.0
Sign command: /usr/lib/linux-kbuild-6.1/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
Certificate or key are missing, generating self signed certificate for MOK...
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/rtl8192eu/1.0/source/dkms.conf)

Building module:
Cleaning build area...
'make' all KVER=6.1.0-rpi4-rpi-v8....(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.1.0-rpi4-rpi-v8 (aarch64)
Consult /var/lib/dkms/rtl8192eu/1.0/build/make.log for more information.
root@plex:/home/jan/tlwn8200nddriver# cat /var/lib/dkms/rtl8192eu/1.0/build/make.log
DKMS make.log for rtl8192eu-1.0 for kernel 6.1.0-rpi4-rpi-v8 (aarch64)
Sat 21 Oct 20:21:19 BST 2023
make ARCH=aarch64 CROSS_COMPILE= -C /lib/modules/6.1.0-rpi4-rpi-v8/build M=/var/lib/dkms/rtl8192eu/1.0/build  modules
make[1]: Entering directory '/usr/src/linux-headers-6.1.0-rpi4-rpi-v8'
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_cmd.o
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service.h:45,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_cmd.c:22:
/var/lib/dkms/rtl8192eu/1.0/build/core/rtw_cmd.c: In function ‘rtw_cmd_thread’:
/var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:165:31: error: implicit declaration of function ‘complete_and_exit’ [-Werror=implicit-function-declaration]
  165 |         #define thread_exit() complete_and_exit(NULL, 0)
      |                               ^~~~~~~~~~~~~~~~~
/var/lib/dkms/rtl8192eu/1.0/build/core/rtw_cmd.c:759:9: note: in expansion of macro ‘thread_exit’
  759 |         thread_exit();
      |         ^~~~~~~~~~~
/var/lib/dkms/rtl8192eu/1.0/build/core/rtw_cmd.c:761:1: error: control reaches end of non-void function [-Werror=return-type]
  761 | }
      | ^
cc1: some warnings being treated as errors
make[2]: *** [/usr/src/linux-headers-6.1.0-rpi4-common-rpi/scripts/Makefile.build:255: /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_cmd.o] Error 1
make[1]: *** [/usr/src/linux-headers-6.1.0-rpi4-common-rpi/Makefile:2039: /var/lib/dkms/rtl8192eu/1.0/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.1.0-rpi4-rpi-v8'
make: *** [Makefile:1700: modules] Error 2
```

**Comment by SLAYER-CODE** [comment]
https://github.com/clnhub/rtl8192eu-linux
